services:
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    env_file:
      - .env
    command: redis-server  --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - mynet
  
  nextapp:
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    depends_on:
      - app
    networks:
      - mynet
  app:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynet

  db:
    restart: always
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  db_data:
